[workspace]
members = ["crates/bip39-ceremony-core"]
resolver = "3"

[package]
name = "bip39-ceremony-tui"
version = "0.1.0"
edition = "2024"
rust-version = "1.94"
license = "MIT"
publish = false

[[bin]]
name = "bip39-ceremony"
path = "src/main.rs"

[dependencies]
bitcoin_hashes = { version = "=0.14.0", default-features = false }
bip39-ceremony-core = { version = "=0.1.0", path = "crates/bip39-ceremony-core" }
termion = { version = "=4.0.6", default-features = false }
zeroize = { version = "=1.9.0", default-features = false, features = ["alloc"] }

[lints]
workspace = true

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
cargo = { level = "warn", priority = -1 }
cognitive_complexity = "deny"
pedantic = { level = "warn", priority = -1 }
